update config

diff --git a/lf/.config/lf/lfrc b/lf/.config/lf/lfrc
--- a/lf/.config/lf/lfrc
+++ b/lf/.config/lf/lfrc
@@ -246,6 +246,45 @@ cmd paste &{{
     esac
     rm ~/.local/share/lf/files
     lf -remote "send clear"
+    lf -remote "send reload"
+}}
+copy_selected_file() {
+    # Check if an argument (the selected file) is provided
+    if [ -z "$1" ]; then
+        echo "No file selected."
+        return 1
+    fi
+
+    # Prompt the user for a name for the copied file
+    read -p "Enter a name for the copied file: " new_file_name
+
+    # Copy the selected file to the specified name
+    cp "$1" "$new_file_name"
+
+    if [ $? -eq 0 ]; then
+        echo "File copied successfully!"
+    else
+        echo "Error copying file."
+    fi
+}
+cmd lf-copy ${{
+    # Check if an argument (the selected file) is provided
+    if [ -z "$fx" ]; then
+        echo "No file selected."
+        return 1
+    fi
+
+    # Prompt the user for a name for the copied file
+    read -p "Enter a name for the copied file: " new_file_name
+
+    # Copy the selected file to the specified name
+    cp "$fx" "$new_file_name"
+
+    if [ $? -eq 0 ]; then
+        echo "File copied successfully!"
+    else
+        echo "Error copying file."
+    fi
 }}
 
 # Bindings
@@ -288,6 +327,7 @@ map U unselect
 map f fzf_jump
 map se sudoedit
 map e edit
+map cc lf-copy
 # JUMP 
 map gtr cd ~/.local/share/Trash/files
 map gw cd ~/.config/wall
